### ISSUE TITLE
Unintended UI Behavior After Interacting with ComposeFragment_Notification

### ISSUE THREAD

**Issue by SidharthMudgil** [th3kumar/Snoozz-Sleeping-Buddy#17] opened 2023-10-03 10:08 UTC
https://github.com/th3kumar/Snoozz-Sleeping-Buddy/assets/68889544/a556b9cb-cfae-4943-af76-113ccd291f51

**Comment by th3kumar** [comment] 2023-10-03 10:30
> yg.mp4

Hi @SidharthMudgil 
Thank you for bringing this to our attention🌟. Based on the screen recording you provided, it appears that there may be a state management bug. To assist further, could you please provide a detailed account of the sequence of actions you performed leading up to encountering this issue? 
This information will be invaluable in helping us pinpoint and resolve the problem effectively.

**Comment by SidharthMudgil** [comment] 2023-10-03 11:22
I was just checking out the app so I can't recall exact steps...

1. Open the create screen
2. played 5-7 audio.
3. close all audio except one & click on home button.
4. open the app again. [I think I also playaround with notification]
5. found issue.... 

Btw nice assets you used in the app... Do you created all those illustrations, animations, and icons? If not provide the source.

**Comment by th3kumar** [comment] 2023-10-03 12:06
> I was just checking out the app so I can't recall exact steps...
> 
> 1. Open the create screen
> 2. played 5-7 audio.
> 3. close all audio except one & click on home button.
> 4. open the app again. [I think I also playaround with notification]
> 5. found issue....
> 
> Btw nice assets you used in the app... Do you created all those illustrations, animations, and icons? If not provide the source.

Thank you once again for your valuable input. We would greatly appreciate it if you could also consider giving our repository a star on GitHub.

Regarding the assets in the app, I primarily sourced them from **Icons8** and **Freepik** for icons and illustrations, and for animations, we utilized **Lottiefiles**. While we don't have a detailed folder of assets and their sources readily available at the moment, we will consider creating one for future reference.

**Comment by th3kumar** [comment] 2023-10-03 12:17
hi @SidharthMudgil 

We've investigated the issue, and it appears that the problem is indeed related to the app's handling of notifications, and we will work on resolving it promptly.

**Closed as completed** 2023-12-06 07:21 UTC
